<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="all_features" errors="0" failures="52" tests="74">
    <testcase classname="assertion_macros.cpp" name="normal macros">
      <failure type="CHECK">
        assertion_macros.cpp(13): Expression throw_if(true, std::runtime_error("whops!")) == 42 became 
      </failure>
      <failure message="Approx( 0.502 ) == 0.501" type="CHECK">
        assertion_macros.cpp(22): Expression doctest::Approx(0.502) == 0.501 became Approx( 0.502 ) == 0.501
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="expressions should be evaluated only once"/>
    <testcase classname="assertion_macros.cpp" name="exceptions-related macros">
      <failure type="CHECK_THROWS">
        assertion_macros.cpp(33): Expression throw_if(false, 0) became 
      </failure>
      <failure type="CHECK_THROWS_AS">
        assertion_macros.cpp(35): Expression throw_if(true, 0) became 
      </failure>
      <failure type="CHECK_THROWS_AS">
        assertion_macros.cpp(36): Expression throw_if(false, 0) became 
      </failure>
      <failure type="CHECK_THROWS_WITH">
        assertion_macros.cpp(38): Expression throw_if(true, "whops!") became 
      </failure>
      <failure type="CHECK_THROWS_WITH_AS">
        assertion_macros.cpp(39): Expression throw_if(true, "whops!") became 
      </failure>
      <failure type="CHECK_THROWS_WITH_AS">
        assertion_macros.cpp(40): Expression throw_if(true, "whops!") became 
      </failure>
      <failure type="CHECK_NOTHROW">
        assertion_macros.cpp(42): Expression throw_if(true, 0) became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="exceptions-related macros for std::exception">
      <failure type="CHECK_THROWS">
        assertion_macros.cpp(47): Expression throw_if(false, 0) became 
      </failure>
      <failure type="CHECK_THROWS_AS">
        assertion_macros.cpp(48): Expression throw_if(false, std::runtime_error("whops!")) became 
      </failure>
      <failure type="CHECK_THROWS_AS">
        assertion_macros.cpp(50): Expression throw_if(true, std::runtime_error("whops!")) became 
      </failure>
      <failure type="CHECK_THROWS_WITH">
        assertion_macros.cpp(52): Expression throw_if(false, "") became 
      </failure>
      <failure type="REQUIRE_NOTHROW">
        assertion_macros.cpp(54): Expression throw_if(true, std::runtime_error("whops!")) became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="WARN level of asserts don't fail the test case">
      <failure message="0" type="WARN">
        assertion_macros.cpp(62): Expression 0 became 0
      </failure>
      <failure message="1" type="WARN_FALSE">
        assertion_macros.cpp(63): Expression 1 became 1
      </failure>
      <failure type="WARN_THROWS">
        assertion_macros.cpp(64): Expression throw_if(false, 0) became 
      </failure>
      <failure type="WARN_THROWS_WITH">
        assertion_macros.cpp(65): Expression throw_if(true, "") became 
      </failure>
      <failure type="WARN_THROWS_WITH">
        assertion_macros.cpp(66): Expression throw_if(false, "") became 
      </failure>
      <failure type="WARN_THROWS_AS">
        assertion_macros.cpp(67): Expression throw_if(false, 0) became 
      </failure>
      <failure type="WARN_THROWS_AS">
        assertion_macros.cpp(68): Expression throw_if(true, 0) became 
      </failure>
      <failure type="WARN_THROWS_WITH_AS">
        assertion_macros.cpp(69): Expression throw_if(false, "") became 
      </failure>
      <failure type="WARN_THROWS_WITH_AS">
        assertion_macros.cpp(70): Expression throw_if(true, "") became 
      </failure>
      <failure type="WARN_NOTHROW">
        assertion_macros.cpp(71): Expression throw_if(true, 0) became 
      </failure>
      <failure message="1, 0" type="WARN_EQ">
        assertion_macros.cpp(73): Expression 1, 0 became 1, 0
      </failure>
      <failure message="0" type="WARN_UNARY">
        assertion_macros.cpp(74): Expression 0 became 0
      </failure>
      <failure message="1" type="WARN_UNARY_FALSE">
        assertion_macros.cpp(75): Expression 1 became 1
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="CHECK level of asserts fail the test case but don't abort it">
      <failure message="0" type="CHECK">
        assertion_macros.cpp(79): Expression 0 became 0
      </failure>
      <failure message="1" type="CHECK_FALSE">
        assertion_macros.cpp(80): Expression 1 became 1
      </failure>
      <failure type="CHECK_THROWS">
        assertion_macros.cpp(81): Expression throw_if(false, 0) became 
      </failure>
      <failure type="CHECK_THROWS_AS">
        assertion_macros.cpp(82): Expression throw_if(false, 0) became 
      </failure>
      <failure type="CHECK_THROWS_AS">
        assertion_macros.cpp(83): Expression throw_if(true, 0) became 
      </failure>
      <failure type="CHECK_THROWS_WITH">
        assertion_macros.cpp(84): Expression throw_if(true, 0) became 
      </failure>
      <failure type="CHECK_THROWS_WITH_AS">
        assertion_macros.cpp(85): Expression throw_if(true, 0) became 
      </failure>
      <failure type="CHECK_NOTHROW">
        assertion_macros.cpp(86): Expression throw_if(true, 0) became 
      </failure>
      <failure message="1, 0" type="CHECK_EQ">
        assertion_macros.cpp(88): Expression 1, 0 became 1, 0
      </failure>
      <failure message="0" type="CHECK_UNARY">
        assertion_macros.cpp(89): Expression 0 became 0
      </failure>
      <failure message="1" type="CHECK_UNARY_FALSE">
        assertion_macros.cpp(90): Expression 1 became 1
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 1">
      <failure message="0" type="REQUIRE">
        assertion_macros.cpp(96): Expression 0 became 0
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 2">
      <failure message="1" type="REQUIRE_FALSE">
        assertion_macros.cpp(100): Expression 1 became 1
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 3">
      <failure type="REQUIRE_THROWS">
        assertion_macros.cpp(104): Expression throw_if(false, 0) became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 4">
      <failure type="REQUIRE_THROWS_AS">
        assertion_macros.cpp(108): Expression throw_if(false, 0) became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 5">
      <failure type="REQUIRE_THROWS_AS">
        assertion_macros.cpp(112): Expression throw_if(true, 0) became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 6">
      <failure type="REQUIRE_THROWS_WITH">
        assertion_macros.cpp(116): Expression throw_if(false, "") became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 7">
      <failure type="REQUIRE_THROWS_WITH">
        assertion_macros.cpp(120): Expression throw_if(true, "") became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 8">
      <failure type="REQUIRE_THROWS_WITH_AS">
        assertion_macros.cpp(124): Expression throw_if(false, "") became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 9">
      <failure type="REQUIRE_THROWS_WITH_AS">
        assertion_macros.cpp(128): Expression throw_if(true, "") became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 10">
      <failure type="REQUIRE_NOTHROW">
        assertion_macros.cpp(132): Expression throw_if(true, 0) became 
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 11">
      <failure message="1, 0" type="REQUIRE_EQ">
        assertion_macros.cpp(136): Expression 1, 0 became 1, 0
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 12">
      <failure message="0" type="REQUIRE_UNARY">
        assertion_macros.cpp(140): Expression 0 became 0
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="REQUIRE level of asserts fail and abort the test case - 13">
      <failure message="1" type="REQUIRE_UNARY_FALSE">
        assertion_macros.cpp(144): Expression 1 became 1
      </failure>
    </testcase>
    <testcase classname="assertion_macros.cpp" name="all binary assertions"/>
    <testcase classname="assertion_macros.cpp" name="some asserts used in a function called by a test case">
      <failure type="CHECK_THROWS_WITH_AS">
        assertion_macros.cpp(183): Expression throw_if(true, false) became 
      </failure>
    </testcase>
  </testsuite>
</testsuites>
Program code.
