<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="all_features" errors="1" failures="1" tests="12">
    <testcase classname="test_cases_and_suites.cpp" name="an empty test that will succeed - not part of a test suite"/>
    <testcase classname="test_cases_and_suites.cpp" name="should fail because of an exception">
      <error message="exception">
        0
      </error>
    </testcase>
    <testcase classname="test_cases_and_suites.cpp" name="fixtured test - not part of a test suite">
      <failure message="21 == 85" type="CHECK">
        test_cases_and_suites.cpp(42): Expression data == 85 became 21 == 85
      </failure>
    </testcase>
    <testcase classname="test_cases_and_suites.cpp" name="part of scoped"/>
    <testcase classname="test_cases_and_suites.cpp" name="part of scoped 2"/>
    <testcase classname="test_cases_and_suites.cpp" name="unskipped"/>
    <testcase classname="test_cases_and_suites.cpp" name="skipped - inherited from the test suite"/>
    <testcase classname="test_cases_and_suites.cpp" name="part of some TS"/>
    <testcase classname="test_cases_and_suites.cpp" name="fails - and its allowed"/>
    <testcase classname="test_cases_and_suites.cpp" name="doesn't fail which is fine"/>
    <testcase classname="test_cases_and_suites.cpp" name="fails as it should"/>
    <testcase classname="test_cases_and_suites.cpp" name="doesn't fail but it should have"/>
    <testcase classname="test_cases_and_suites.cpp" name="fails 1 time as it should"/>
    <testcase classname="test_cases_and_suites.cpp" name="fails more times as it should"/>
    <testcase classname="test_cases_and_suites.cpp" name="normal test in a test suite from a decorator"/>
  </testsuite>
</testsuites>
Program code.
